// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useState, useEffect, useRef } from 'react';
import React from 'react';
import { Link, Text, useSitecore, AppPlaceholder, RichText, NextImage, withDatasourceCheck, CdpHelper } from '@sitecore-content-sdk/nextjs';
import componentMap from '.sitecore/component-map';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import { event, identity, pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import Cookies from 'js-cookie';
import { UpdateGuestExtensionV2, GetGuestDetails, AddGuestExtension, CheckGuestExistsInCDP, UpdateGuestExtension, UpdateGuestExtensionV6, UpdateGuestExtensionV5, UpdateGuestExtensionV3, UpdateGuestExtensionV4 } from 'src/lib/cdp/cdpService';
import { getNextPageFromExperience } from 'src/lib/personalize/personalizeService';
import client from 'src/lib/sitecore-client';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useEffect', value: useEffect },
      { name: 'useRef', value: useRef },
      { name: 'default', value: React },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'event', value: event },
      { name: 'identity', value: identity },
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'js-cookie',
    exports: [
      { name: 'default', value: Cookies },
    ]
  },
  {
    module: 'src/lib/cdp/cdpService',
    exports: [
      { name: 'UpdateGuestExtensionV2', value: UpdateGuestExtensionV2 },
      { name: 'GetGuestDetails', value: GetGuestDetails },
      { name: 'AddGuestExtension', value: AddGuestExtension },
      { name: 'CheckGuestExistsInCDP', value: CheckGuestExistsInCDP },
      { name: 'UpdateGuestExtension', value: UpdateGuestExtension },
      { name: 'UpdateGuestExtensionV6', value: UpdateGuestExtensionV6 },
      { name: 'UpdateGuestExtensionV5', value: UpdateGuestExtensionV5 },
      { name: 'UpdateGuestExtensionV3', value: UpdateGuestExtensionV3 },
      { name: 'UpdateGuestExtensionV4', value: UpdateGuestExtensionV4 },
    ]
  },
  {
    module: 'src/lib/personalize/personalizeService',
    exports: [
      { name: 'getNextPageFromExperience', value: getNextPageFromExperience },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
